
import numpy as np
import torch
from torch.utils.data import Dataset
import os.path
import imageio
from misc import imutils
import json
import time
import pickle
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
IMG_FOLDER_NAME = "images"
IGNORE = 255

CAT_LIST = ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush']

N_CAT = len(CAT_LIST)

CAT_NAME_TO_NUM = dict(zip(CAT_LIST,range(len(CAT_LIST))))

def _generate_cls_labels(coco_root, train_list_path, val_list_path):
    """
    Generates the cls_labels.npy file if it doesn't exist. Includes a lock file mechanism.
    """
    current_dir = os.path.dirname(os.path.abspath(__file__))
    cls_labels_path = os.path.join(current_dir, 'cls_labels.npy')
    lock_path = os.path.join(current_dir, 'cls_labels.lock')

    # Wait if the lock file exists
    while os.path.exists(lock_path):
        print("Waiting for cls_labels.npy to be generated by another process...")
        time.sleep(5)

    if os.path.exists(cls_labels_path):
        try:
            return np.load(cls_labels_path, allow_pickle=True).item()
        except (EOFError, pickle.UnpicklingError):
            print("Warning: cls_labels.npy is corrupted. Deleting and regenerating.")
            os.remove(cls_labels_path)

    # Create the lock file
    with open(lock_path, 'w') as f:
        f.write('locked')

    print("cls_labels.npy not found or corrupted. Generating it from COCO annotations...")

    try:
        def load_coco_annotations(ann_file):
            if not os.path.exists(ann_file):
                print(f"Warning: Annotation file not found at {ann_file}. Skipping.")
                return {}
            
            with open(ann_file, 'r') as f:
                ann_data = json.load(f)
            
            img_id_to_name = {img['id']: img['file_name'].replace('.jpg', '') for img in ann_data['images']}
            cat_id_to_name = {cat['id']: cat['name'] for cat in ann_data['categories']}
            
            # --- DEBUGGING: Print some annotation examples ---
            print(f"\n--- DEBUG: Annotations from {os.path.basename(ann_file)} ---")
            print(f"Total images in annotation: {len(img_id_to_name)}")
            sample_ids = list(img_id_to_name.keys())[:5]
            print("Sample image names from annotation (expected format):")
            for id in sample_ids:
                print(f"  {img_id_to_name[id]}")
            print("---------------------------------------------------\n")
            
            img_labels = {}
            for ann in ann_data['annotations']:
                img_id = ann['image_id']
                cat_id = ann['category_id']
                
                if img_id not in img_id_to_name:
                    continue

                img_name = img_id_to_name[img_id]
                
                if cat_id not in cat_id_to_name:
                    continue
                cat_name = cat_id_to_name[cat_id]

                if img_name not in img_labels:
                    img_labels[img_name] = np.zeros(N_CAT, dtype=np.float32)
                
                if cat_name in CAT_NAME_TO_NUM:
                    cat_num = CAT_NAME_TO_NUM[cat_name]
                    img_labels[img_name][cat_num] = 1.0
                else:
                    raise ValueError(f"Unknown category name {cat_name}")

            for items in img_labels.keys():
                if img_labels[items].all() == 0.0:
                    print('Empty labels')
                    print("item", items)

                if not img_labels[items].any() == 1.0:
                    print('Empty labels')
                    print("item", items)
            return img_labels

        train_ann_path = os.path.join(coco_root, "annotations", "instances_train2017.json")
        val_ann_path = os.path.join(coco_root, "annotations", "instances_val2017.json")

        train_labels = load_coco_annotations(train_ann_path)
        val_labels = load_coco_annotations(val_ann_path)

        all_labels = {**train_labels, **val_labels}
        
        train_names = load_img_name_list(train_list_path)
        val_names = load_img_name_list(val_list_path)
        
        # --- DEBUGGING: Print some directory examples ---
        print(f"\n--- DEBUG: Image Names from Directory ---")
        print(f"Total training images found: {len(train_names)}")
        print("Sample image names from train_names (actual format):")
        for name in list(train_names)[:5]:
            print(f"  {name}")
        print("-----------------------------------------\n")
        
        all_names = set(np.concatenate((train_names, val_names)))

        final_labels = {}
        missing_count = 0
        empty_label_count = 0
        
        for name in all_names:
            if name in all_labels:
                if np.sum(all_labels[name]) > 0:
                    final_labels[name] = all_labels[name]
                else:
                    empty_label_count += 1
            else:
                missing_count += 1
                
        print(f"Found {len(final_labels)} images with valid labels.")
        print(f"Dropped {empty_label_count} images because they had no positive labels.")
        print(f"Warning: {missing_count} images from the directories were NOT found in the annotation files!")


        if not final_labels:
            raise ValueError("No valid labels were loaded. Please check your COCO dataset paths and annotations.")

        np.save(cls_labels_path, final_labels)
        print(f"Successfully generated and saved cls_labels.npy with {len(final_labels)} entries.")
        
        # Remove the lock file
        os.remove(lock_path)
        
        return final_labels

    except Exception as e:
        # Clean up lock file on error
        if os.path.exists(lock_path):
            os.remove(lock_path)
        raise e


def get_img_path(img_name, coco_root):
    # Assuming COCO 2017 folder structure
    train_img_path = os.path.join(coco_root, 'train2017', img_name + '.jpg')
    val_img_path = os.path.join(coco_root, 'val2017', img_name + '.jpg')
    if os.path.exists(train_img_path):
        return train_img_path
    elif os.path.exists(val_img_path):
        return val_img_path
    else:
        # Fallback for older/different structures
        return os.path.join(coco_root, IMG_FOLDER_NAME, img_name + '.jpg')


def load_img_name_list(dataset_path):
    if os.path.isfile(dataset_path):
        img_name_list = np.loadtxt(dataset_path, dtype=str)
    elif os.path.isdir(dataset_path):
        print(f"Loading image names from directory: {dataset_path}")
        img_name_list = [os.path.splitext(f)[0] for f in os.listdir(dataset_path) if f.endswith('.jpg')]
        if not img_name_list:
            print(f"Warning: No .jpg images found in directory {dataset_path}.")
    else:
        raise FileNotFoundError(f"Dataset path not found: {dataset_path}. It must be a file or a directory.")
    return np.array(img_name_list)


class TorchvisionNormalize():
    def __init__(self, mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)):
        self.mean = mean
        self.std = std

    def __call__(self, img):
        imgarr = np.asarray(img)
        proc_img = np.empty_like(imgarr, np.float32)

        proc_img[..., 0] = (imgarr[..., 0] / 255. - self.mean[0]) / self.std[0]
        proc_img[..., 1] = (imgarr[..., 1] / 255. - self.mean[1]) / self.std[1]
        proc_img[..., 2] = (imgarr[..., 2] / 255. - self.mean[2]) / self.std[2]

        return proc_img

class COCOImageDataset(Dataset):

    def __init__(self, img_name_list_path, coco_root,
                 resize_long=None, resize_scale=None, rescale=None, img_normal=TorchvisionNormalize(), hor_flip=False,
                 crop_size=None, crop_method=None, to_torch=True):

        self.img_name_list = load_img_name_list(img_name_list_path)
        self.coco_root = coco_root

        self.resize_long = resize_long
        self.rescale = rescale
        self.resize_scale = resize_scale
        self.crop_size = crop_size
        self.img_normal = img_normal
        self.hor_flip = hor_flip
        self.crop_method = crop_method
        self.to_torch = to_torch

    def __len__(self):
        return len(self.img_name_list)

    def __getitem__(self, idx):
        name = self.img_name_list[idx]
        
        img_path = get_img_path(name, self.coco_root)
        try:
            img = np.asarray(imageio.imread(img_path))

            if img.ndim == 2:
                # Convert Grayscale (H, W) to RGB (H, W, 3)
                img = np.stack((img,) * 3, axis=-1)

        except FileNotFoundError:
            print(f"FATAL: Image not found at {img_path}")
            return {'name': name, 'img': torch.zeros((3, self.crop_size, self.crop_size)) if self.crop_size else torch.zeros((3, 224, 224))}


        if self.resize_long:
            img = imutils.random_resize_long(img, self.resize_long[0], self.resize_long[1])
        
        if self.resize_scale:
            img = imutils.resize_scale(img, resize_scale=self.resize_scale)

        if self.rescale:
            img = imutils.random_scale(img, scale_range=self.rescale, order=3)

        if self.img_normal:
            img = self.img_normal(img)

        if self.hor_flip:
            img = imutils.random_lr_flip(img)

        if self.crop_size:
            if self.crop_method == "random":
                img = imutils.random_crop(img, self.crop_size, 0)
            else:
                img = imutils.top_left_crop(img, self.crop_size, 0)
        
        if self.to_torch:
            img = imutils.HWC_to_CHW(img)

        return {'name': name, 'img': img}

class COCOClassificationDataset(COCOImageDataset):

    def __init__(self, img_name_list_path, coco_root,
                 resize_long=None, resize_scale=None, rescale=None, img_normal=TorchvisionNormalize(), hor_flip=False,
                 crop_size=None, crop_method=None):
        super().__init__(img_name_list_path, coco_root,
                 resize_long, resize_scale, rescale, img_normal, hor_flip,
                 crop_size, crop_method)
        
        val_list_path = img_name_list_path.replace('train', 'val') if 'train' in img_name_list_path else img_name_list_path

        self.cls_labels_dict = _generate_cls_labels(coco_root, img_name_list_path, val_list_path)

        self.label_list = np.array([self.cls_labels_dict[img_name] for img_name in self.img_name_list if img_name in self.cls_labels_dict])
        
        original_len = len(self.img_name_list)
        self.img_name_list = [name for name in self.img_name_list if name in self.cls_labels_dict]
        if len(self.img_name_list) != original_len:
            print(f"Warning: Dropped {original_len - len(self.img_name_list)} images from the dataset because they were missing labels.")


    def __getitem__(self, idx):
        out = super().__getitem__(idx)

        if 'img' in out:# and torch.is_tensor(out['img']):
             if out['name'] in self.cls_labels_dict:
                out['label'] = torch.from_numpy(self.cls_labels_dict[out['name']])
             else:
                out['label'] = torch.zeros(N_CAT, dtype=torch.float32)
                raise ValueError("Not found in cls_label_dics" + out['name'])
        else:
            out['label'] = torch.zeros(N_CAT, dtype=torch.float32)
            raise ValueError("img not found in" + str(out))

        return out


class COCOClassificationDatasetMSF(COCOClassificationDataset):

    def __init__(self, img_name_list_path, coco_root,
                 img_normal=TorchvisionNormalize(),
                 scales=(1.0,)):
        self.scales = scales
        # Initialize the parent class COCOClassificationDataset
        super().__init__(img_name_list_path, coco_root, img_normal=img_normal)
        self.scales = scales

    def __getitem__(self, idx):
        name = self.img_name_list[idx]

        # Use the get_img_path function already defined in your dataloader
        img_path = get_img_path(name, self.coco_root)
        img = np.asarray(imageio.imread(img_path))

        # Handle grayscale images just like in COCOImageDataset
        if img.ndim == 2:
            img = np.stack((img,) * 3, axis=-1)

        ms_img_list = []
        for s in self.scales:
            s_img = imutils.pil_rescale(img, s, order=3)
            s_img = self.img_normal(s_img)
            s_img = imutils.HWC_to_CHW(s_img)
            # Create a stack of the scaled image and its horizontally flipped version
            ms_img_list.append(np.stack([s_img, np.flip(s_img, -1)], axis=0))

        if len(self.scales) == 1:
            ms_img_list = ms_img_list[0]

        # Fetch the label from the dictionary generated in the parent class
        out = {"name": name,
               "img": ms_img_list,
               "size": (img.shape[0], img.shape[1]),
               "label": torch.from_numpy(self.cls_labels_dict[name])}
        return out

# 1. The Helper Class
class COCOGetAffinityLabelFromIndices():
    def __init__(self, indices_from, indices_to, num_classes=81):
        self.indices_from = indices_from
        self.indices_to = indices_to
        self.num_classes = num_classes

    def __call__(self, segm_map):
        segm_map_flat = np.reshape(segm_map, -1)

        segm_label_from = np.expand_dims(segm_map_flat[self.indices_from], axis=0)
        segm_label_to = segm_map_flat[self.indices_to]

        valid_label = np.logical_and(np.less(segm_label_from, self.num_classes), np.less(segm_label_to, self.num_classes))

        equal_label = np.equal(segm_label_from, segm_label_to)

        pos_affinity_label = np.logical_and(equal_label, valid_label)

        bg_pos_affinity_label = np.logical_and(pos_affinity_label, np.equal(segm_label_from, 0)).astype(np.float32)
        fg_pos_affinity_label = np.logical_and(pos_affinity_label, np.greater(segm_label_from, 0)).astype(np.float32)

        neg_affinity_label = np.logical_and(np.logical_not(equal_label), valid_label).astype(np.float32)

        return torch.from_numpy(bg_pos_affinity_label), torch.from_numpy(fg_pos_affinity_label), \
               torch.from_numpy(neg_affinity_label)

# 2. The Missing Parent Class
class COCOSegmentationDataset(Dataset):
    def __init__(self, img_name_list_path, label_dir, crop_size, coco_root,
                 rescale=None, img_normal=TorchvisionNormalize(), hor_flip=False,
                 crop_method='random'):

        raw_img_name_list = load_img_name_list(img_name_list_path)
        self.coco_root = coco_root
        self.label_dir = label_dir
        self.rescale = rescale
        self.crop_size = crop_size
        self.img_normal = img_normal
        self.hor_flip = hor_flip
        self.crop_method = crop_method

        # --- Filter out missing images and labels ---
        print("Validating dataset files... this might take a moment.")
        self.img_name_list = []
        missing_count = 0

        for name in raw_img_name_list:
            img_path = get_img_path(name, self.coco_root)
            label_path = os.path.join(self.label_dir, name + '.png')

            # Check if BOTH the raw image and the generated pseudo-label exist
            if img_path and os.path.exists(img_path) and os.path.exists(label_path):
                self.img_name_list.append(name)
            else:
                missing_count += 1

        print(f"Dataset initialized: {len(self.img_name_list)} valid samples. Skipped {missing_count} missing samples.")

    def __len__(self):
        return len(self.img_name_list)

    def __getitem__(self, idx):
        name = self.img_name_list[idx]

        img_path = get_img_path(name, self.coco_root)
        try:
            img = np.asarray(imageio.imread(img_path))
            if img.ndim == 2:
                img = np.stack((img,) * 3, axis=-1)
        except FileNotFoundError:
            # We shouldn't hit this anymore due to pre-filtering, but keeping it as a fallback
            print(f"FATAL: Image not found at {img_path}")
            img = np.zeros((self.crop_size or 224, self.crop_size or 224, 3), dtype=np.uint8)

        label_path = os.path.join(self.label_dir, name + '.png')
        label = imageio.imread(label_path)

        if self.rescale:
            img, label = imutils.random_scale((img, label), scale_range=self.rescale, order=(3, 0))

        if self.img_normal:
            img = self.img_normal(img)

        if self.hor_flip:
            img, label = imutils.random_lr_flip((img, label))

        if self.crop_method == "random":
            img, label = imutils.random_crop((img, label), self.crop_size, (0, 255))
        else:
            img = imutils.top_left_crop(img, self.crop_size, 0)
            label = imutils.top_left_crop(label, self.crop_size, 255)

        img = imutils.HWC_to_CHW(img)

        return {'name': name, 'img': img, 'label': label}

# 3. The Child Class (which threw the error)
class COCOAffinityDataset(COCOSegmentationDataset):
    def __init__(self, img_name_list_path, label_dir, crop_size, coco_root,
                 indices_from, indices_to,
                 rescale=None, img_normal=TorchvisionNormalize(), hor_flip=False, crop_method=None):
        super().__init__(img_name_list_path, label_dir, crop_size, coco_root, rescale, img_normal, hor_flip, crop_method=crop_method)

        self.extract_aff_lab_func = COCOGetAffinityLabelFromIndices(indices_from, indices_to, num_classes=N_CAT + 1)

    def __len__(self):
        return len(self.img_name_list)

    def __getitem__(self, idx):
        out = super().__getitem__(idx)

        reduced_label = imutils.pil_rescale(out['label'], 0.25, 0)

        out['aff_bg_pos_label'], out['aff_fg_pos_label'], out['aff_neg_label'] = self.extract_aff_lab_func(reduced_label)

        return out